config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end
  def answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<% if params[:question] == "i am going to work" %>
<%= "great" %>
<% elsif params[:question].include?("?") %>
<%= "Silly question, get dressed and go to work!" %>
<% else %>
<%= "I don't care, get dressed and go to work!" %>
<% end %>

<%= link_to "ask", ask_path %>

app/views/questions/ask.html.erb
<h1>Stupid Coasching</h1>
<form class="ask" action="/answer">
  <dev class="ask_1">
  <input type="text" name="question" >
  </dev>
  <dev>
  <input id="answer_1" type="submit" value="Ask!">
  </dev>
</form>